channels:
- conda-forge
- nodefaults
dependencies:
# !! you can only use single `=` to set a version. Otherwise it will break the update job
- invoke=2.2.0
- packaging
- pyyaml
# applications
- jupyterlab=4.0.10
- jupyter-collaboration=2.0.1
- nbconvert=7.14.1
- notebook=7.0.6
# extensions
- jupyter-offlinenotebook=0.2.2
- jupyterlab-fasta=3.3
- jupyterlab-geojson=3.4
# Python Kernel
- ipykernel=6.28.0
- xeus-python=0.14.3
- ipywidgets=8
- ipyleaflet=0.18.1
- altair=5.2.0
- bqplot=0.12.42
- dask=2024.1.0
- matplotlib-base=3.8.2
- pandas=2.1.4
- python=3.9
- scikit-image=0.22.0
- scikit-learn=1.3.2
- seaborn-base=0.13.1
- tensorflow=2.11.0
- sympy=1.12
- traittypes=0.2.1
# C++ Kernel
- xeus-cling=0.13.0
- xtensor=0.23.10
- xtensor-blas=0.19.2
- xwidgets=0.26.1
- xleaflet=0.16.0
# CLI tools
- pip
- vim
