channels:
- conda-forge
- nodefaults
dependencies:
# !! you can only use single `=` to set a version. Otherwise it will break the update job
- invoke=2.2.0
- packaging
- pyyaml
# applications
- jupyterlab=4.0.9
- jupyter-collaboration=1.0.1
- nbconvert=7.6.0
- notebook=7.0.6
# extensions
- jupyter-offlinenotebook=0.2.2
- jupyterlab-fasta=3.3
- jupyterlab-geojson=3.4
# Python Kernel
- ipykernel=6.24.0
- xeus-python=0.14.3
- ipywidgets=8
- ipyleaflet=0.17.3
- altair=5.0.1
- bqplot=0.12.40
- dask=2023.7.0
- matplotlib-base=3.7.1
- pandas=2.0.3
- python=3.9
- scikit-image=0.21.0
- scikit-learn=1.3.0
- seaborn-base=0.12.2
- tensorflow=2.11.0
- sympy=1.12
- traittypes=0.2.1
# C++ Kernel
- xeus-cling=0.13.0
- xtensor=0.23.10
- xtensor-blas=0.19.2
- xwidgets=0.26.1
- xleaflet=0.16.0
# CLI tools
- pip
- vim
