channels:
- conda-forge
- nodefaults
dependencies:
# !! you can only use single `=` to set a version. Otherwise it will break the update job
- invoke=2.2.0
- packaging
- pyyaml
# applications
- jupyterlab=4.1.5
- jupyter-collaboration=2.0.3
- nbconvert=7.16.2
- notebook=7.1.1
# extensions
- jupyter-offlinenotebook=0.3.1
- jupyterlab-fasta=3.3
- jupyterlab-geojson=3.4
# Python Kernel
- ipykernel=6.29.3
- xeus-python=0.14.3
- ipywidgets=8
- ipyleaflet=0.18.2
- altair=5.2.0
- bqplot=0.12.43
- dask=2024.3.0
- matplotlib-base=3.8.3
- pandas=2.2.1
- python=3.9
- scikit-image=0.22.0
- scikit-learn=1.4.1.post1
- seaborn-base=0.13.2
- tensorflow=2.11.0
- sympy=1.12
- traittypes=0.2.1
# C++ Kernel
- xeus-cling=0.13.0
- xtensor=0.23.10
- xtensor-blas=0.19.2
- xwidgets=0.26.1
- xleaflet=0.16.0
# CLI tools
- pip
- vim
