channels:
- conda-forge
- nodefaults
dependencies:
# !! you can only use single `=` to set a version. Otherwise it will break the update job
- invoke=1.7.3
- packaging
- pyyaml
# applications
- jupyterlab=3.5.0
- retrolab=0.3.21
- nbconvert=7.2.5
# extensions
- jupyter-offlinenotebook=0.2
- jupyterlab-fasta=3.2.0
- jupyterlab-geojson=3.3.1
- jupyterlab-link-share=0.2
# Python Kernel
- ipykernel=6.17.1
- xeus-python=0.14.3
- ipywidgets=8.0.2
- widgetsnbextension=4.0.3
- ipyleaflet=0.17.2
- altair=4.2.0
- bqplot=0.12.36
- dask=2022.11.0
- matplotlib-base=3.6.2
- pandas=1
- python=3.9
- scikit-image=0.19.3
- scikit-learn=1.1.3
- seaborn=0.12.1
- tensorflow=2
- sympy=1.11.1
- traittypes=0.2.1
# C++ Kernel
- xeus-cling=0.13.0
- xtensor=0.23.10
- xtensor-blas=0.19.2
- xwidgets=0.26.1
- xleaflet=0.16.0
# CLI tools
- vim
