channels:
- conda-forge
- nodefaults
dependencies:
# !! you can only use single `=` to set a version. Otherwise it will break the update job
- invoke
- packaging
- pyyaml
# applications
- jupyterlab
- jupyter-collaboration
- nbconvert
- notebook
# extensions
- jupyter-offlinenotebook
- jupyterlab-fasta
- jupyterlab-geojson
# Python Kernel
- ipykernel
- xeus-python
- ipywidgets
- ipyleaflet
- altair
- bqplot
- dask
- matplotlib-base
- pandas
- python=3.12
- scikit-image
- scikit-learn
- seaborn-base
- tensorflow
- sympy
- traittypes
# C++ Kernel
# - xeus-cling
# - xtensor
# - xtensor-blas
# - xwidgets
# - xleaflet
# CLI tools
- pip
- vim
