channels:
- conda-forge
- nodefaults
dependencies:
# !! you can only use single `=` to set a version. Otherwise it will break the update job
- invoke=1.2
- packaging
- pyyaml
# applications
- jupyterlab=3.2
- retrolab=0.3
- nbconvert=6
# extensions
- jupyter-offlinenotebook=0.2
- jupyterlab-fasta=3.1
- jupyterlab-geojson=3.1
- jupyterlab-link-share=0.2
# Python Kernel
- ipykernel=6.5
- xeus-python=0.9
- ipywidgets=7.6
- widgetsnbextension=3.5
- ipyleaflet=0.13
- altair=4.1
- bqplot=0.12.20
- dask=2020.12
- matplotlib-base=3.1
- pandas=1
- python=3.7
- scikit-image=0.15
- scikit-learn=0.21
- seaborn=0.11
- tensorflow=1.14
- sympy=1.4
- traittypes=0.2.1
# C++ Kernel
- xeus-cling=0.10
- xtensor=0.20.8
- xtensor-blas=0.16.1
- xwidgets=0.24.2
- xleaflet=0.13.1
# CLI tools
- vim
